<?php namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Credit extends Model
{
    
	public $table = "credits";

	public $primaryKey = "id";
    
	public $timestamps = true;

	public $fillable = [
	    "adviser",											
		"date",
		"folio",
		"branch",
		"ammount",
		"interest_rate",
		"dues",		
		"periodicity",
		"warranty_type",
		"firts_name",
		"last_name",
		"mothers_last_name",
		"curp",
		"ine",
		"civil_status",
		"scholarship",
		"phone",
		"dependents",
		"no_familys",
		"type_of_housing",
		"street",
		"number",
		"colony",
		"municipality",
		"state",
		"postal_code",		
		"references",
		"street_company",
		"number_company",
		"colony_company",
		"municipality_company",
		"state_company",
		"postal_code_company",
		"phone_company",
		"name_company",
		"inventory",
		"maq_equi",
		"vehicles",
		"property",
		"box_benck",
		"accounts",
		"suppliers",
		"credits",
		"payments",
		"specify",
		"weekday",
		"weekend",
		"utility",
		"other_income",
		"rent",
		"salary",
		"others",
		"name_aval",
		"last_name_aval",
		"mothers_name_aval",
		"birthdate_aval",
		"curp_aval",
		"phone_aval",
		"civil_status_aval",
		"scholarship_aval",
		"street_aval",
		"number_aval",
		"colony_aval",
		"municipality_aval",
		"state_aval",
		"postal_code_aval",
		"firts_name_reference",
		"last_name_reference",
		"mothers_last_name_reference",
		"phone_reference",
		"firts_name_reference2",
		"last_name_reference2",
		"mothers_last_name_reference2",
		"phone_reference2",
		"collection_period",
		"firm",
		"status",
		"client_id"
	];

	public static $rules = [
	    "adviser" => "required",
		"date" => "required",
		"branch" => "required",
		"ammount" => "required",
		"interest_rate" => "required",
		"dues" => "required",		
		"periodicity" => "required",
		"warranty_type" => "required",
		"firts_name" => "required",
		"last_name" => "required",
		"mothers_last_name" => "required",
		"curp" => "required",
		"ine" => "required",
		"civil_status" => "required",
		"scholarship" => "required",
		"phone" => "required",
		"dependents" => "required",
		"no_familys" => "required",
		"type_of_housing" => "required",
		"street" => "required",
		"number" => "required",
		"colony" => "required",
		"municipality" => "required",
		"state" => "required",
		"postal_code" => "required",
		"references" => "required",
		"street_company" => "required",
		"number_company" => "required",
		"colony_company" => "required",
		"municipality_company" => "required",
		"state_company" => "required",
		"postal_code_company" => "required",
		"phone_company" => "required",
		"name_company" => "required",
		"inventory" => "required",
		"maq_equi" => "required",
		"vehicles" => "required",
		"property" => "required",
		"box_benck" => "required",
		"accounts" => "required",
		"suppliers" => "required",
		"credits" => "required",
		"payments" => "required",
		"specify" => "required",
		"weekday" => "required",
		"weekend" => "required",
		"utility" => "required",
		"other_income" => "required",
		"rent" => "required",
		"salary" => "required",
		"others" => "required",
		"name_aval" => "required",
		"last_name_aval" => "required",
		"mothers_name_aval" => "required",
		"birthdate_aval" => "required",
		"curp_aval" => "required",
		"phone_aval" => "required",
		"civil_status_aval" => "required",
		"scholarship_aval" => "required",
		"street_aval" => "required",
		"number_aval" => "required",
		"colony_aval" => "required",
		"municipality_aval" => "required",
		"state_aval" => "required",
		"postal_code_aval" => "required",
		"firts_name_reference" => "required",
		"last_name_reference" => "required",
		"mothers_last_name_reference" => "required",
		"phone_reference" => "required",
		"collection_period" => "required",
		"status" => "required",
		"firm" => "required"
	];

	 public function client()
    {
        return $this->belongsTo('App\Models\Client');
    }
}
